[project]
name = "pynergy-client"
version = "0.1.5"
description = "A python client for synergy protocol"
requires-python = ">=3.13"
dependencies = [
    "pynergy-protocol",
    "evdev>=1.9.2; sys_platform == 'linux'",
    "loguru>=0.7.3",
    "platformdirs>=4.5.0",
    "typer>=0.21.0",
    "cryptography>=46.0.3",
    "questionary>=2.1.1",
]

[project.scripts]
pynergy-client = "pynergy_client.__main__:app"

[build-system]
requires = ["hatchling>=1.18"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pynergy_client"]

[tool.hatch.build]
artifacts = [
    "src/pynergy_client/locales/**/*.mo",
]

[tool.uv.sources]
pynergy-protocol = { workspace = true }
