[project]
name = "pynergy-protocol"
version = "0.1.5"
description = "Core synergy protocol definitions for python (Pynergy)"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
]

[build-system]
requires = ["hatchling>=1.18"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pynergy_protocol"]
